[project]
name = "projet2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.7",
    "requests>=2.32.5",
    "scikit-learn>=1.8.0",
    "streamlit>=1.52.0",
    "streamlit-option-menu>=0.4.0",
]
